---
title: "Homework2_613"
author: "Elizabeth Marge"
date: "2/14/2021"
output: word_document

---


## Question 1 


```{r}

library(tidyverse)


```


```{r}

USArrests

## The type of information that is shown within the USArrests dataset is there are rows for all 50 states in the United States. For the columns, this includes murder, assault, urbanpop, and rape variables that are evaulated for each state. 

```

## Question 2 

```{r}

map_dbl(USArrests$Assault, max)

## North Carolina has the largest number of assaults. 

```


## Question 3

```{r}

library(nycflights13)
flights

```

## Question 4

```{r}

nrow(flights)
ncol(flights)

```

```{r}

## Tibbles do not change variable names or types, and show more frequent errors when a variable does not exists. This forces a tibble to have cleaner and a more expressive structure. In addition, tibbles have an enhanced print() function that makes it easier to utilize with large datasets that can contain complex objects. 

is_tibble(flights)

```
## Question 5

```{r}

typeof(ncol(flights))


```

## Question 6

```{r}

as_tibble(iris)

```


```{r}

## Response- sepal.length
## Predictor - sepal.width (you are predicting length making it the y variable )

sepal <- lm(Sepal.Length~Sepal.Width, iris)
sepal

```

```{r}

models1 <- iris %>%
  split(.$Species) %>%
  map(~lm(Sepal.Length~Sepal.Width, data = .))
models1

```


## Question 7

```{r}

V <- list(12, 22, 27, 31.5, NA, 39, "east")
V

```

## 7A- 

```{r}

length(c(12, 22, 27, 31.5, NA, 39, "east"))

```

## 7B

```{r}

V[is.na(V)]

```


## 7c

```{r}

V[3]


```


## 7D

```{r}


str(V[c(1,7)])


```


## 7E


```{r}


typeof("east")

```

